---
title: "Music Data Project"
author: "Thomas Schechter"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r}
#Start by loading packages

library(pacman)

p_load(readr,data.table,tidyverse,ggplot2,tidymodels,ranger,parsnip,purrr,magrittr,lubridate,parallel,pbapply,stringr)

#We'll add more as needed
```
```{r}
#Make sure you commit to your repo

#After that, it's time to load in datasets

#Imported directly from the directory on the bottom-right
```

```{r}
#Peruse the data, get a feel for it all. It's a lot...

glimpse(lyrics_data)

lyrics_sum <- summary(lyrics_data)

lyrics_sum

#It's all character data in lyrics_data

artists_sum <- artists_data %>% summary()

artists_sum

#3/5 is character, 2/5 is numerical
```

```{r}
#continue onto genre and album review datasets

genre_sum <- music_genre %>% summary()

reviews_sum <- music_album_reviews %>% summary()

genre_sum

#some character, mostly numerical data
```

```{r}

reviews_sum

#1 column characters (the review), 1 column numeric (The rating)

#Interesting that 4.0 is the first quartile in review rating... people like what they listen to?

#mean is somewhat below the median for this data set. Let's check it out.
```
```{r}
#let's do some visualization
 #First, simplify the name of the dataset

rev_data <- music_album_reviews

#find the length of each review. We're going to plot that against the rating each album recieved in the review

rev_data$rev_length <- str_length(rev_data$Review)

rev_data %>% glimpse()

rating_chart <- ggplot(rev_data, aes(x=rev_length,y=Rating, color=rev_length)) + geom_boxplot() + facet_wrap(vars(Rating))


rating_chart
```
```{r}
#Let's do some cleaning. 
#Impute to remove any NAs with the mean of the Ratings

rev_data$Rating[is.na(rev_data$Rating)] <- mean(rev_data$Rating, na.rm=T)

anyNA(rev_data$Rating)

#We now can see we have no missing values and can use the data with assurance it's clean

rev_data$bad_review <- ifelse(rev_data$rev_length<=140,print("TRUE"),print("FALSE"))
                              
view(rev_data)
```

```{r}

```


```{r}
#How many cores are we working with?

detectCores(all.tests = FALSE, logical = TRUE)

#12. Cool. Let's use 10

cls <- makeCluster(10)


```






MUSIC GENRES

```{r}
#Let's make this easier to understand

genre_data <- music_genre

summary(genre_data)

#Let's change the tempo to numeric data

genre_data$tempo <- genre_data$tempo %>% as.numeric()

#Don't forget to eliminate missing values (impute)

genre_data$tempo[is.na(genre_data$tempo)] <- mean(genre_data$tempo, na.rm=T)

anyNA(genre_data$tempo)

#SUCCESS
```
```{r}
#What is the most represented genre in the dataset?

genre_data$electr <- ifelse(genre_data$music_genre=="Electronic","TRUE","FALSE")

view(genre_data)

#See what other genres are here, and repeat for all

#unique(genre_data$music_genre)

#genre_data$blues <- ifelse(genre_data$music_genre=="Blues","TRUE","FALSE")
#genre_data$anime <- ifelse(genre_data$music_genre=="Anime","TRUE","FALSE")
#genre_data$rock <- ifelse(genre_data$music_genre=="Rock","TRUE","FALSE")
#genre_data$alt <- ifelse(genre_data$music_genre=="Alternative","TRUE","FALSE")
#genre_data$country <- ifelse(genre_data$music_genre=="Country","TRUE","FALSE")
#genre_data$classical <- ifelse(genre_data$music_genre=="Classical","TRUE","FALSE")
#genre_data$rap <- ifelse(genre_data$music_genre=="Rap","TRUE","FALSE")
#genre_data$hiphop <- ifelse(genre_data$music_genre=="Hip-Hop","TRUE","FALSE")

#view(genre_data)

#Now it's easier to find the number of rows and we have more options


#Above is entirely unnecessary... just use this below
elect_num <- nrow(filter(genre_data,music_genre=="Electronic"))
blues_num <- nrow(filter(genre_data,music_genre=="Blues"))
classic_num <- nrow(filter(genre_data,music_genre=="Classical"))
rock_num <-nrow(filter(genre_data,music_genre=="Rock"))
anime_num <- nrow(filter(genre_data,music_genre=="Anime"))
rap_num <- nrow(filter(genre_data,music_genre=="Rap"))
hiphop_num <- nrow(filter(genre_data,music_genre=="Hip-Hop"))
country_num <-nrow(filter(genre_data,music_genre=="Country"))
alt_num <- nrow(filter(genre_data,music_genre=="Alternative"))

elect_num
blues_num
hiphop_num
rock_num
rap_num
country_num
alt_num
anime_num
classic_num


#It seems there's 5k of each genre. It probably said this somewhere in the data description, but I missed that
```

```{r}
#visualize?

genre_plot1 <- ggplot(genre_data, aes(x=energy,y=popularity, color=music_genre)) + geom_point() + facet_wrap(vars(key)) 


genre_plot1

#Wow... this is cluttered.

```

